FROM python:3.14.4-alpine

WORKDIR app/

COPY requirements.txt .

RUN pip install -r requirements.txt

COPY ./src/ ./src/
COPY pyproject.toml .

# 8000 = app, 9000 = metrics. Docs only.
EXPOSE 8000 9000

CMD ["fastapi", "dev", "--host", "0.0.0.0"]