name: Build and Deploy

on:
  push:
    branches: [main, staging]

jobs:
  deploy:
    permissions:
      packages: write
      contents: read
    uses: b-zago/actions/.github/workflows/box-deployment.yml@v1
    with:
      patToken: ${{ secrets.PAT_TOKEN }}
    secrets: inherit
